import jsPDF from 'jspdf';
import { Anomaly } from '@/types/database';

export function generateAuditDossierPDF(anomalies: Anomaly[], batchName = 'PLFS 2023-Q4 Microdata Batch') {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('SurvIntel — Official Survey Audit Dossier', 14, 15);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('NATIONAL SAMPLE SURVEY OFFICE (NSSO) • MINISTRY OF STATISTICS & PROGRAMME IMPLEMENTATION', 14, 23);
  doc.text(`Batch Reference: ${batchName} | Date: ${new Date().toLocaleDateString()}`, 14, 29);

  // Summary Metrics Box
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 42, 182, 24, 3, 3, 'FD');

  const hardCount = anomalies.filter((a) => a.severity === 'hard').length;
  const softCount = anomalies.filter((a) => a.severity === 'soft').length;
  const openCount = anomalies.filter((a) => a.status === 'open' || a.status === 'in_review').length;

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(`TOTAL FLAGGED ANOMALIES: ${anomalies.length}`, 20, 52);
  doc.text(`HARD CHECK VIOLATIONS: ${hardCount}`, 80, 52);
  doc.text(`SOFT QUALITY FLAGS: ${softCount}`, 140, 52);

  doc.setFont('helvetica', 'normal');
  doc.text(`OPEN RESOLUTION ITEMS: ${openCount}`, 20, 60);
  doc.text(`AUDIT COMPLIANCE STATUS: ${hardCount === 0 ? 'CLEARED' : 'ACTION REQUIRED'}`, 80, 60);

  // Anomaly Listing Table Header
  let y = 76;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Flagged Microdata Anomalies Detail Listing', 14, y);

  y += 6;
  doc.setFillColor(30, 41, 59); // slate-800
  doc.rect(14, y, 182, 8, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('RULE CODE', 16, y + 5.5);
  doc.text('SEVERITY', 45, y + 5.5);
  doc.text('DISTRICT / PSU', 70, y + 5.5);
  doc.text('ENUMERATOR', 115, y + 5.5);
  doc.text('SCORE', 145, y + 5.5);
  doc.text('STATUS', 170, y + 5.5);

  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(30, 41, 59);

  for (let i = 0; i < Math.min(anomalies.length, 18); i++) {
    const item = anomalies[i];
    if (i % 2 === 1) {
      doc.setFillColor(241, 245, 249);
      doc.rect(14, y, 182, 7, 'F');
    }

    doc.text(item.rule_code, 16, y + 4.5);
    doc.text(item.severity.toUpperCase(), 45, y + 4.5);
    doc.text(`${(item.district || 'N/A').substring(0, 18)} (${item.psu_id || 'N/A'})`, 70, y + 4.5);
    doc.text(item.enumerator_id || 'N/A', 115, y + 4.5);
    doc.text(`${(item.score * 100).toFixed(0)}%`, 145, y + 4.5);
    doc.text(item.status.toUpperCase(), 170, y + 4.5);

    y += 7;
  }

  // Footer Signature Line
  doc.setDrawColor(203, 213, 225);
  doc.line(14, 270, 196, 270);

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by SurvIntel Automated Data Audit Platform • NSSO Survey Division', 14, 276);
  doc.text('Page 1 of 1', 180, 276);

  doc.save(`survintel_audit_dossier_${batchName.toLowerCase().replace(/\s+/g, '_')}.pdf`);
}
